### ISSUE TITLE
bug: feature flags not respected

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#65]
With something listening on port 3000 and specifying a different port, krustlet-wascc and krustlet-wasi both seem to ignore these parameters, reverting to the default values.

```
><> ../../target/debug/krustlet-wascc --help
krustlet 0.1.0
A kubelet for running WebAssembly workloads

USAGE:
    krustlet-wascc [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -a, --addr <addr>              The address krustlet should listen on [env: KRUSTLET_ADDRESS=]  [default: 0.0.0.0]
        --hostname <hostname>      The hostname for this node, defaults to the hostname of this machine [env: KRUSTLET_HOSTNAME=]
    -n, --node-ip <node-ip>        The IP address of the node registered with the Kubernetes master. Defaults to the IP address of the node name in DNS as a best effort try at a default [env: KRUSTLET_NODE_IP=]
        --node-name <node-name>    The name for this node in Kubernetes, defaults to the hostname of this machine [env: KRUSTLET_NODE_NAME=]
    -p, --port <port>              The port krustlet should listen on [env: KRUSTLET_PORT=]  [default: 3000]
```

```
><> ../../target/debug/krustlet-wascc --port 8080
[2020-03-12T22:48:14Z ERROR kubelet::node] Error creating node: ApiError: nodes "ultralisk" already exists: AlreadyExists (ErrorResponse { status: "Failure", message: "nodes \"ultralisk\" already exists", reason: "AlreadyExists", code: 409 })
[2020-03-12T22:48:14Z ERROR kubelet::node] Failed to create lease: ApiError: leases.coordination.k8s.io "ultralisk" already exists: AlreadyExists (ErrorResponse { status: "Failure", message: "leases.coordination.k8s.io \"ultralisk\" already exists", reason: "AlreadyExists", code: 409 })
thread 'main' panicked at 'error binding to 0.0.0.0:3000: error creating server listener: Address already in use (os error 98)', /home/bacongobbler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.3/src/server/mod.rs:124:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The same issue appears when using environment variables.

```
><> export KRUSTLET_PORT=8080
><> ../../target/debug/krustlet-wascc 
[2020-03-12T22:52:22Z ERROR kubelet::node] Error creating node: ApiError: nodes "ultralisk" already exists: AlreadyExists (ErrorResponse { status: "Failure", message: "nodes \"ultralisk\" already exists", reason: "AlreadyExists", code: 409 })
[2020-03-12T22:52:22Z ERROR kubelet::node] Failed to create lease: ApiError: leases.coordination.k8s.io "ultralisk" already exists: AlreadyExists (ErrorResponse { status: "Failure", message: "leases.coordination.k8s.io \"ultralisk\" already exists", reason: "AlreadyExists", code: 409 })
thread 'main' panicked at 'error binding to 0.0.0.0:3000: error creating server listener: Address already in use (os error 98)', /home/bacongobbler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.3/src/server/mod.rs:124:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rylev** [comment]
This is fixed by #64
