### ISSUE TITLE
bug(wascc): panicked on an `Err` value: Error(HostCallFailure("bad dispatch")

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#79]
Running `just test-e2e` on master displays the following error from the wascc provider:

```
     Running `/home/bacongobbler/code/krustlet/target/debug/krustlet-wascc --node-name krustlet-wascc --port 3000`
[2020-03-17T21:51:16Z INFO  wascc_host::capability] Loaded capability: wascc:http_server, native provider: waSCC Default HTTP Server (Actix Web)
[2020-03-17T21:51:16Z INFO  wascc_host::host] Native capability provider 'wascc:http_server' ready
[2020-03-17T21:51:27Z DEBUG wascc_provider] Pod added "hello-wascc"
[2020-03-17T21:51:27Z DEBUG wascc_provider] "MB4OLDIC3TCZ4Q4TGGOVAZC43VXFE2JQVRAXQMQFXUCREOOFEKOKZTY2"
[2020-03-17T21:51:27Z INFO  wascc_provider] Starting containers for pod "hello-wascc"
[2020-03-17T21:51:27Z DEBUG wascc_provider] Starting container hello-wascc on thread
[2020-03-17T21:51:27Z INFO  wascc_provider] wascc run
[2020-03-17T21:51:27Z INFO  wascc_host::authz] Discovered capability attestations: wascc:http_server
[2020-03-17T21:51:27Z INFO  wascc_host::host] Native capability provider 'wascc:extras' ready
[2020-03-17T21:51:27Z INFO  wascc_host::host] Adding actor MB4OLDIC3TCZ4Q4TGGOVAZC43VXFE2JQVRAXQMQFXUCREOOFEKOKZTY2 to host
[2020-03-17T21:51:27Z INFO  wascc_host::host] Loading actor module...
[2020-03-17T21:51:29Z INFO  wascc_host::host] Actor MB4OLDIC3TCZ4Q4TGGOVAZC43VXFE2JQVRAXQMQFXUCREOOFEKOKZTY2 ready for communications
[2020-03-17T21:51:29Z INFO  wascc_provider] configuring capability wascc:http_server
[2020-03-17T21:51:29Z INFO  wascc_host::host] Attempting to configure actor MB4OLDIC3TCZ4Q4TGGOVAZC43VXFE2JQVRAXQMQFXUCREOOFEKOKZTY2 for capability wascc:http_server
[2020-03-17T21:51:29Z INFO  wascc_host::host] Capability wascc:http_server received invocation for target wascc:http_server
[2020-03-17T21:51:29Z INFO  wascc_provider] Instance executing
[2020-03-17T21:51:29Z INFO  wascc_provider] All containers started for pod "hello-wascc". Updating status
[2020-03-17T21:51:29Z INFO  wascc_provider] Pod modified
[2020-03-17T21:51:29Z INFO  wascc_provider] Modified pod spec: PodStatus {
        conditions: Some(
            [
                PodCondition {
                    last_probe_time: None,
                    last_transition_time: Some(
                        Time(
                            2020-03-17T21:51:27Z,
                        ),
                    ),
                    message: None,
                    reason: None,
                    status: "True",
                    type_: "PodScheduled",
                },
            ],
        ),
        container_statuses: None,
        ephemeral_container_statuses: None,
        host_ip: None,
        init_container_statuses: None,
        message: None,
        nominated_node_name: None,
        phase: Some(
            "Pending",
        ),
        pod_ip: None,
        pod_ips: None,
        qos_class: Some(
            "BestEffort",
        ),
        reason: None,
        start_time: None,
    }
[2020-03-17T21:51:29Z INFO  wascc_provider] Pod modified
[2020-03-17T21:51:29Z INFO  wascc_provider] Modified pod spec: PodStatus {
        conditions: Some(
            [
                PodCondition {
                    last_probe_time: None,
                    last_transition_time: Some(
                        Time(
                            2020-03-17T21:51:27Z,
                        ),
                    ),
                    message: None,
                    reason: None,
                    status: "True",
                    type_: "PodScheduled",
                },
            ],
        ),
        container_statuses: None,
        ephemeral_container_statuses: None,
        host_ip: None,
        init_container_statuses: None,
        message: None,
        nominated_node_name: None,
        phase: Some(
            "Pending",
        ),
        pod_ip: None,
        pod_ips: None,
        qos_class: Some(
            "BestEffort",
        ),
        reason: None,
        start_time: None,
    }
[2020-03-17T21:51:29Z INFO  wascc_host::host] Terminating actor MB4OLDIC3TCZ4Q4TGGOVAZC43VXFE2JQVRAXQMQFXUCREOOFEKOKZTY2
[2020-03-17T21:51:29Z INFO  wascc_host::host] Capability wascc:http_server received invocation for target wascc:http_server
[2020-03-17T21:51:29Z INFO  wascc_host::host] Capability wascc:extras received invocation for target wascc:extras
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(HostCallFailure("bad dispatch"))', /home/bacongobbler/.cargo/registry/src/github.com-1ecc6299db9ec823/wascc-host-0.5.2/src/middleware.rs:45:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/bacongobbler/.cargo/registry/src/github.com-1ecc6299db9ec823/wascc-host-0.5.2/src/host.rs:520:24
```

**Comment by bacongobbler** [comment]
Hmm... Looking at the error more closely, this looks like an error coming upstream from [`wascc-host`](https://github.com/wascc/wascc-host).

**Comment by rylev** [comment]
I can't seem to reproduce this.

**Comment by bacongobbler** [comment]
Can't reproduce anymore either... Weird! Will close for now
